import { upsertCatalogBooks } from "./catalog-memory.js";

const seededBooks = [
  {
    id: 1,
    title: "The Left Hand of Darkness",
    authors: ["Ursula K. Le Guin"],
    genres: ["Science Fiction", "Political", "Classic"],
    starRating: 4.1,
    ratingCount: 358000,
    progress: 70,
  },
  {
    id: 2,
    title: "Piranesi",
    authors: ["Susanna Clarke"],
    genres: ["Fantasy", "Mystery", "Literary"],
    starRating: 4.2,
    ratingCount: 312000,
    myRating: 5,
    progress: 40,
  },
  {
    id: 3,
    title: "The Fifth Season",
    authors: ["N. K. Jemisin"],
    genres: ["Fantasy", "Science Fiction", "Apocalyptic"],
    starRating: 4.3,
    ratingCount: 289000,
    myRating: 4,
    progress: 20,
  },
  {
    id: 4,
    title: "A Visit from the Goon Squad",
    authors: ["Jennifer Egan"],
    genres: ["Literary", "Experimental", "Contemporary"],
    starRating: 3.9,
    ratingCount: 146000,
    progress: 10,
  },
  {
    id: 5,
    title: "The Name of the Rose",
    authors: ["Umberto Eco"],
    genres: ["Historical", "Mystery", "Classic"],
    starRating: 4,
    ratingCount: 163000,
    myRating: 4,
    progress: 55,
  },
  {
    id: 6,
    title: "Sea of Tranquility",
    authors: ["Emily St. John Mandel"],
    genres: ["Science Fiction", "Literary", "Time Travel"],
    starRating: 4.1,
    ratingCount: 228000,
    progress: 30,
  },
  {
    id: 7,
    title: "Tomorrow, and Tomorrow, and Tomorrow",
    authors: ["Gabrielle Zevin"],
    genres: ["Contemporary", "Literary", "Friendship"],
    starRating: 4.2,
    ratingCount: 694000,
    myRating: 5,
    progress: 80,
  },
  {
    id: 8,
    title: "Kindred",
    authors: ["Octavia E. Butler"],
    genres: ["Science Fiction", "Historical", "Classic"],
    starRating: 4.3,
    ratingCount: 423000,
    myRating: 5,
    progress: 100,
    read: true,
    readCount: 1,
    lastReadYear: 2023,
    archivedAtYear: 2023,
  },
  {
    id: 9,
    title: "Station Eleven",
    authors: ["Emily St. John Mandel"],
    genres: ["Apocalyptic", "Literary", "Science Fiction"],
    starRating: 4.1,
    ratingCount: 518000,
    myRating: 4,
    progress: 100,
    read: true,
    readCount: 2,
    lastReadYear: 2022,
    archivedAtYear: 2022,
  },
  {
    id: 10,
    title: "The Goldfinch",
    authors: ["Donna Tartt"],
    genres: ["Literary", "Coming-of-Age", "Drama"],
    starRating: 3.9,
    ratingCount: 819000,
    myRating: 3,
    progress: 100,
    read: true,
    readCount: 1,
    lastReadYear: 2021,
    archivedAtYear: 2021,
  },
  {
    id: 11,
    title: "Never Let Me Go",
    authors: ["Kazuo Ishiguro"],
    genres: ["Literary", "Science Fiction", "Dystopian"],
    starRating: 3.8,
    ratingCount: 621000,
    myRating: 5,
    progress: 100,
    read: true,
    readCount: 2,
    lastReadYear: 2024,
    archivedAtYear: 2024,
  },
  {
    id: 12,
    title: "The City & the City",
    authors: ["China Mieville"],
    genres: ["Mystery", "Fantasy", "Political"],
    starRating: 3.9,
    ratingCount: 82000,
    myRating: 4,
    progress: 100,
    read: true,
    readCount: 1,
    lastReadYear: 2020,
    archivedAtYear: 2020,
  },
];

function cloneBooks(books) {
  return books.map((book) => ({
    ...book,
    authors: [...book.authors],
    genres: [...book.genres],
    moods: [...(Array.isArray(book.moods) ? book.moods : [])],
  }));
}

export function createSeedState() {
  return {
    books: cloneBooks(seededBooks),
    catalogBooks: upsertCatalogBooks([], seededBooks),
    genreInterests: {},
    authorExperiences: {},
    seriesExperiences: {},
    meta: {
      seeded: true,
      migratedLocalState: false,
      updatedAt: new Date().toISOString(),
    },
  };
}
